import { downloadTextFile, slugify } from './download'
import type { Obligation } from '../types'

const PRODID = '-//PactPilot//Contract Obligations//EN'
const RRULE_FREQ: Record<string, string> = { weekly: 'WEEKLY', monthly: 'MONTHLY', yearly: 'YEARLY' }

function pad(n: number): string {
  return n < 10 ? `0${n}` : `${n}`
}

/** True only for a real, syntactically valid calendar date (rejects things like 2026-02-30). */
function isValidIsoDate(value: string): boolean {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value)
  if (!m) return false
  const y = Number(m[1])
  const mo = Number(m[2])
  const d = Number(m[3])
  const dt = new Date(Date.UTC(y, mo - 1, d))
  return dt.getUTCFullYear() === y && dt.getUTCMonth() === mo - 1 && dt.getUTCDate() === d
}

function toIcsDate(isoDate: string): string {
  return isoDate.replace(/-/g, '')
}

function addDays(isoDate: string, days: number): string {
  const [y, m, d] = isoDate.split('-').map(Number)
  const dt = new Date(Date.UTC(y, m - 1, d + days))
  return `${dt.getUTCFullYear()}-${pad(dt.getUTCMonth() + 1)}-${pad(dt.getUTCDate())}`
}

function nowStamp(): string {
  const d = new Date()
  return (
    `${d.getUTCFullYear()}${pad(d.getUTCMonth() + 1)}${pad(d.getUTCDate())}T` +
    `${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}${pad(d.getUTCSeconds())}Z`
  )
}

/** Escapes a value for a TEXT property per RFC 5545. Order matters: backslashes first. */
function escapeText(text: string): string {
  return text
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\n/g, '\\n')
}

/** Folds a content line to at most 75 octets per RFC 5545, counting UTF-8 bytes correctly. */
function foldLine(line: string): string {
  const enc = new TextEncoder()
  if (enc.encode(line).length <= 75) return line

  const out: string[] = []
  let current = ''
  let bytes = 0
  let isFirst = true
  for (const ch of line) {
    const chBytes = enc.encode(ch).length
    const limit = isFirst ? 75 : 74
    if (bytes + chBytes > limit) {
      out.push(current)
      current = ''
      bytes = 0
      isFirst = false
    }
    current += ch
    bytes += chBytes
  }
  if (current) out.push(current)
  return out.join('\r\n ')
}

export interface ScheduledObligation {
  title: string
  dueLabel: string
  clauseId: string
  date: string
  recurrence: Obligation['recurrence']
}

/** Only obligations with a real calendar date can become a calendar event. */
export function obligationsWithDates(obligations: readonly Obligation[]): ScheduledObligation[] {
  return obligations
    .filter((o) => o.date !== null && isValidIsoDate(o.date))
    .map((o) => ({
      title: o.title,
      dueLabel: o.dueLabel,
      clauseId: o.clauseId,
      date: o.date as string,
      recurrence: o.recurrence,
    }))
}

/** Builds a standards-compliant .ics file as a string. Events with no date are left out. */
export function buildIcs(obligations: readonly Obligation[], docName: string): string {
  const dated = obligationsWithDates(obligations)
  const stamp = nowStamp()

  const lines: string[] = ['BEGIN:VCALENDAR', 'VERSION:2.0', `PRODID:${PRODID}`, 'CALSCALE:GREGORIAN']

  dated.forEach((o, i) => {
    const desc = [
      o.dueLabel,
      docName ? `Document: ${docName}` : '',
      o.clauseId ? `Clause: ${o.clauseId}` : '',
      'Generated by PactPilot. Information, not legal advice.',
    ]
      .filter(Boolean)
      .join('\n')

    lines.push('BEGIN:VEVENT')
    lines.push(foldLine(`UID:pactpilot-${i}-${o.date}@pactpilot.app`))
    lines.push(`DTSTAMP:${stamp}`)
    lines.push(`DTSTART;VALUE=DATE:${toIcsDate(o.date)}`)
    lines.push(`DTEND;VALUE=DATE:${toIcsDate(addDays(o.date, 1))}`)
    lines.push(foldLine(`SUMMARY:${escapeText(o.title)}`))
    lines.push(foldLine(`DESCRIPTION:${escapeText(desc)}`))
    if (o.recurrence && RRULE_FREQ[o.recurrence]) {
      lines.push(`RRULE:FREQ=${RRULE_FREQ[o.recurrence]}`)
    }
    lines.push('END:VEVENT')
  })

  lines.push('END:VCALENDAR')
  return lines.join('\r\n') + '\r\n'
}

/** Builds the .ics file and starts the browser download. */
export function downloadIcs(obligations: readonly Obligation[], docName: string): void {
  const ics = buildIcs(obligations, docName)
  downloadTextFile(`pactpilot-${slugify(docName)}.ics`, ics, 'text/calendar;charset=utf-8')
}
